version: "3.9"


services:
  kafka-01:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-01
    ports:
      - "9092:9092"
    networks:
      - amqp-net
    environment:
      - KAFKA_NODE_ID=1
      - CLUSTER_ID=4f6985cbce81dbf05605
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-01:9091,2@kafka-02:9091,3@kafka-03:9091
      - KAFKA_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-01:9090,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INNER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_PROCESS_ROLES=controller,broker
    volumes:
      - /home/star/tmp/kafka/data:/var/lib/kafka/data

  kafka-02:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-02
    ports:
      - "9094:9094"
    networks:
      - amqp-net
    environment:
      - KAFKA_NODE_ID=2
      - CLUSTER_ID=4f6985cbce81dbf05605
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-01:9091,2@kafka-02:9091,3@kafka-03:9091
      - KAFKA_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-02:9090,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INNER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_PROCESS_ROLES=controller,broker
    volumes:
      - /home/star/tmp/kafka/data:/var/lib/kafka/data

  kafka-03:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-03
    ports:
      - "9096:9096"
    networks:
      - amqp-net
    environment:
      - KAFKA_NODE_ID=3
      - CLUSTER_ID=4f6985cbce81dbf05605
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-01:9091,2@kafka-02:9091,3@kafka-03:9091
      - KAFKA_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9096
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-03:9090,EXTERNAL://localhost:9096
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INNER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_PROCESS_ROLES=controller,broker
    volumes:
      - /home/star/tmp/kafka/data:/var/lib/kafka/data

networks:
  amqp-net:
    driver: bridge
    name: amqp-net