server:
  port: 8085

spring:
  datasource:
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:passwd_user}
    url: jdbc:mysql://localhost:3306/commerce?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: discount
  data:
    jdbc:
      dialect: mysql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30